apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: data-skim-argo-
spec:
  entrypoint: parallel-worker

  podGC:
    # pod gc strategy must be one of the following
    # * OnPodCompletion - delete pods immediately when pod is completed (including errors/failures)
    # * OnPodSuccess - delete pods immediately when pod is successful
    # * OnWorkflowCompletion - delete pods when workflow is completed
    # * OnWorkflowSuccess - delete pods when workflow is successful
    strategy: OnPodSuccess

  parallelism: 10

  volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
      claimName: pvc-mynfs

  templates:
  - name: data-skim-argo
    inputs:
      parameters:
      - name: files
      - name: it
    script:
      imagePullPolicy: Never
      image: cmsopendata/cmssw_5_3_32
      command: [sh]
      source: |
        source /opt/cms/entrypoint.sh
        sudo chown $USER /mnt/vol
        mkdir workspace
        cd workspace
        git clone -b HcalEcal git://github.com/HepUsfq2021/LEDAnalysis.git
        cd LEDAnalysis/LEDSkimmer
        scram b -j8
        varfiles="{{inputs.parameters.files}}"
        sed -i 's,*files,'$varfiles',g' ledskimmer_cfg.py
        cp ElectronInfoData.root /mnt/vol/ElectronInfoData-$iterator.root
        echo  ls -l /mnt/vol
        ls -l /mnt/vol
      volumeMounts:
      - name: task-pv-storage
        mountPath: /mnt/vol

  - name: parallel-worker
    dag:
      tasks:
